### PR TITLE
Fixes and `Timestamp`

### LINKED ISSUE #43: Fails to compile with `-F schemars -F serde`
When you combine the two features, a dependency on the `time` features seems to be introduced. It has something to do with the `define_generic_wrapper!` macro.

Running on `cargo 1.96.0-nightly (cbb9bb8bd 2026-03-13)`:

```
famedly-rust-utils 
❯ cargo build -F schemars -F serde
   Compiling famedly_rust_utils v1.1.0 (/home/rasmus/Projects/famedly-rust-utils)
error[E0425]: cannot find type `TimeDuration` in this scope
   --> src/duration.rs:142:3
    |
142 |         TimeDuration,
    |         ^^^^^^^^^^^^
    |
   ::: /nix/store/gbl9aj5jk2fzgf0kw1g4w4sqszg3h8nn-rust-nightly-latest-2026-03-19/lib/rustlib/src/rust/library/core/src/time.rs:81:1
    |
 81 | pub struct Duration {
    | ------------------- similarly named struct `StdDuration` defined here
    |
help: a struct with a similar name exists
    |
142 -         TimeDuration,
142 +         StdDuration,
    |

error[E0425]: cannot find type `TimeDuration` in this scope
   --> src/duration.rs:183:3
    |
183 |         TimeDuration,
    |         ^^^^^^^^^^^^
    |
   ::: /nix/store/gbl9aj5jk2fzgf0kw1g4w4sqszg3h8nn-rust-nightly-latest-2026-03-19/lib/rustlib/src/rust/library/core/src/time.rs:81:1
    |
 81 | pub struct Duration {
    | ------------------- similarly named struct `StdDuration` defined here
    |
help: a struct with a similar name exists
    |
183 -         TimeDuration,
183 +         StdDuration,
    |

error[E0425]: cannot find type `TimeDuration` in this scope
   --> src/duration.rs:224:3
    |
224 |         TimeDuration,
    |         ^^^^^^^^^^^^
    |
   ::: /nix/store/gbl9aj5jk2fzgf0kw1g4w4sqszg3h8nn-rust-nightly-latest-2026-03-19/lib/rustlib/src/rust/library/core/src/time.rs:81:1
    |
 81 | pub struct Duration {
    | ------------------- similarly named struct `StdDuration` defined here
    |
help: a struct with a similar name exists
    |
224 -         TimeDuration,
224 +         StdDuration,
    |

error[E0425]: cannot find type `TimeDuration` in this scope
   --> src/duration.rs:265:3
    |
265 |         TimeDuration,
    |         ^^^^^^^^^^^^
    |
   ::: /nix/store/gbl9aj5jk2fzgf0kw1g4w4sqszg3h8nn-rust-nightly-latest-2026-03-19/lib/rustlib/src/rust/library/core/src/time.rs:81:1
    |
 81 | pub struct Duration {
    | ------------------- similarly named struct `StdDuration` defined here
    |
help: a struct with a similar name exists
    |
265 -         TimeDuration,
265 +         StdDuration,
    |

For more information about this error, try `rustc --explain E0425`.
error: could not compile `famedly_rust_utils` (lib) due to 4 previous errors

```

### PR DESCRIPTION
**Pull request by sirewix**
- Add `Timestamp`
- Fix some doc warnings
- Fix compilation error on some features combination (closes #43)
- Release
- Remove description from json schema from `BaseUrl` type and inline it

### CODE REVIEW

**Review by RasmusRendal — COMMENTED** [review]
You can add "this closes #43" to the PR description! :D

File: src/timestamp.rs [hunk 1]
```diff
@@ -0,0 +1,83 @@
+// SPDX-FileCopyrightText: 2026 Famedly GmbH (info@famedly.com)
+//
+// SPDX-License-Identifier: Apache-2.0
+
+//! Wrapper over [`OffsetDateTime`] with RFC3339 JSON representation
+
+// TODO: move to famedly-rust-utils crate
```
Comment (chgrv) [inline src/timestamp.rs]:
```suggestion
```

**Review by mzaniolo — APPROVED** [review]
